Various improvements
lolgab/mill-mima pull request #7
Opened 2021-07-16 15:27 UTC by lefou

2021-07-16 17:42 UTC, lolgab requested changes
Thank you for your kind contribution @lefou 
I left some comments :-)

2021-07-16 17:42 UTC, lolgab commented on mill-mima/src/com/github/lolgab/mill/mima/Mima.scala
> +  def resolvedMimaPreviousArtifacts: T[Agg[PathRef]] = T {
I get the caching argument, but I'm not sure we need to make this configurable at this point ( nobody really asked for it, unless you have a use case ).
Can we make it `private` for now?

2021-07-16 17:42 UTC, lolgab commented on mill-mima/src/com/github/lolgab/mill/mima/Mima.scala
> +    val classes = compile().classes.path // .toIO
There is a leftover comment.
```suggestion
    val classes = compile().classes.path
```

2021-07-16 17:42 UTC, lolgab commented on mill-mima/src/com/github/lolgab/mill/mima/Mima.scala
>        Result.Success(())
What if you deleted all the classes and now you broke binary compatibility completely ?
In this case this code returns `Success` if I'm not mistaken.

Should we just pass an empty folder or something like that to mima so it can perform the check?

2021-07-16 17:42 UTC, lolgab commented on mill-mima/src/com/github/lolgab/mill/mima/Mima.scala
> +      new MiMaLib(runClasspath().map(_.path).filter(os.exists).map(_.toIO))
Can actually happen that `runClasspath()` contains paths that don't exist?
Should it just fail in those cases instead of filtering them out?

2021-07-16 17:42 UTC, lolgab commented on mill-mima/src/com/github/lolgab/mill/mima/Mima.scala
>        Result.Success(())
I'm even tempted to create the `classes` folder if it doesn't exist but I know it's not the right thing.
For sure returning `Success` is not the right way.

2021-07-16 18:37 UTC, lefou commented on mill-mima/src/com/github/lolgab/mill/mima/Mima.scala
> +  def resolvedMimaPreviousArtifacts: T[Agg[PathRef]] = T {
Sure, but having a `resolvedX` target e.g. to prepare going offline, or to provide the artifact by some other means (e.g. when offline, or when it needs to be fetched from some internal infrastructure) is some best practice, IMHO. Only public targets can be called from command line, though.

2021-07-16 20:50 UTC, lefou commented on mill-mima/src/com/github/lolgab/mill/mima/Mima.scala
>        Result.Success(())
Oh yeah, I haven't though about that. For me, it was essential to not fail in case of zero classfiles. I'll change that.

2021-07-16 20:53 UTC, lefou commented on mill-mima/src/com/github/lolgab/mill/mima/Mima.scala
> +      new MiMaLib(runClasspath().map(_.path).filter(os.exists).map(_.toIO))
Yes, they exists and no, we should not fail in all cases. E.g. resources directories are part of the run classpath and are in most cases defined (per default) but may not exists.

2021-07-16 21:09 UTC, lefou commented on mill-mima/src/com/github/lolgab/mill/mima/Mima.scala
> +  def resolvedMimaPreviousArtifacts: T[Agg[PathRef]] = T {
Did I convinced you to keep in public? If not, I'd rather make it `protected` to give the user a way to customize the fetch process.

2021-07-16 21:19 UTC, lefou commented on mill-mima/src/com/github/lolgab/mill/mima/Mima.scala
>        Result.Success(())
Updated

2021-07-16 21:46 UTC, lolgab commented on mill-mima/src/com/github/lolgab/mill/mima/Mima.scala
> +  def resolvedMimaPreviousArtifacts: T[Agg[PathRef]] = T {
> e.g. to prepare going offline

For this we can redefine the `prepareOffline` as you did in the other PR.

> when it needs to be fetched from some internal infrastructure

For this just just need to redefine the repositories for the task, right?

> Only public targets can be called from command line, though.

Sure, but I prefer to keep this library minimal and maintain less things as possible.
Even caching, after all, is not that big of a need, since Coursier already downloads and stores the artifacts in its cache.

I'd say, let's revert this change and leave it inline until there is need for it to be in a separate task.

2021-07-16 21:49 UTC, lolgab commented on mill-mima/src/com/github/lolgab/mill/mima/Mima.scala
> +      s"Scanning ${classesCount} classfiles for binary compatibility in ${classes} ..."
Also having all this logic to walk the files just to write a log that the original Sbt plugin doesn't log, doesn't seem worth it to me.
I would remove classesCount completely 🙈

2021-07-16 21:53 UTC, lefou commented on mill-mima/src/com/github/lolgab/mill/mima/Mima.scala
> +      s"Scanning ${classesCount} classfiles for binary compatibility in ${classes} ..."
Fine. I'll revert. I never used the sbt plugin and just tried to make some useful output, which feels rather consistent with what compile and others log out.

2021-07-17 13:09 UTC, lolgab commented
Thank you very much for addressing the comments!
I'm sorry for having been harsh in the review. It's tough to be an Open Source maintainer, isn't it?
On one side I want to express how much thankful I am for your kind contribution, on the other side I still want the project to be how I see it in my head.

About the `resolvedMimaPreviousArtifacts` being `private`, let's wait for a request and then we reevaluate.

Since this morning I merged another PR, I can rebase this for you since it's not fair putting this on you.

2021-07-17 15:00 UTC, lolgab approved these changes

2021-07-17 15:04 UTC, merged

2021-07-17 16:10 UTC, lefou commented
Don't worry to much. Although public, someone needs to maintain the project, and it's no fun to maintain something one does not like. It's always a learning process, on both sides. Thanks for merging!