Added support to resolve multiple previous artifacts
lolgab/mill-mima pull request #9
Opened 2021-07-16 16:48 UTC by lefou

Those may also have same organization and name and only differ in their version.

Also extended the integration test to cover this case.

This PR is draft, as it depends on merging of PR #7. Once #7 is merged, I can rebase and cleanup.

2021-07-17 16:31 UTC, lefou commented
@lolgab I'm sorry to nag you about the visibility again, but to create a proper test for the resolution of multiple artifacts, I initially used the accessible `resolvedMimaPreviousArtifacts` target to check the fetched jars. That way, I could produce a failing test to show that the current implementation did not work sufficiently. Now, that this target is no longer accessible, I have no idea how to hook into the dependency chain to make proper assertions. I commented the relevant assert out in `itest/src/simple/build.sc`.

2021-07-17 17:29 UTC, lefou commented on itest/src/simple/build.sc
> +  // assert(curr.resolvedMimaPreviousArtifacts().size == 3)
Here we need a way to assert the successful resolution/fetch of the three different jars.

2021-07-21 17:23 UTC, lolgab requested changes

2021-07-21 17:23 UTC, lolgab commented on itest/src/simple/build.sc
> +  // assert(curr.resolvedMimaPreviousArtifacts().size == 3)
To check that the bug is fixed we can have a binary incompatibility in version `0.0.1` but not in version `0.0.2`
Without the fix, in this case, the command returns successfully, after the fix it should report the binary incompatibility with the older version.

Like:

`curr.scala`:

```scala
object Main {}
```

`prev.scala` version `0.0.1`:

```scala
object Main {
  def hello(): String = "Hello world!"
}
```

`prev.scala` version `0.0.2`:

```scala
object Main {}
```

2021-07-21 17:23 UTC, lolgab commented on mill-mima/src/com/github/lolgab/mill/mima/Mima.scala
> +    //    val pCustomizer = resolutionCustomizer()
Why did you comment the `resolutionCustomizer`?

2021-07-21 17:23 UTC, lolgab commented on mill-mima/src/com/github/lolgab/mill/mima/Mima.scala
> +        p._1.exclude("*" -> "*") -> p._2.iterator.next
Since we are implementing the resolution manually, we can use `.withTransitive(false)` instead of `.exclude("*" -> "*")`.

2021-07-21 17:23 UTC, lolgab commented on mill-mima/src/com/github/lolgab/mill/mima/Mima.scala
> +  }
This can be extracted as a separate PR

2021-07-21 17:23 UTC, lolgab commented on itest/src/simple/build.sc
> +  def mimaPreviousArtifacts = T(
Instead of modifying the `simple` test, can we have a copy and call it like `multiple-previous-artifacts` just to test this fix?

2021-07-21 17:23 UTC, lolgab commented on mill-mima/src/com/github/lolgab/mill/mima/Mima.scala
> +      sources: Boolean = false
I don't think we need the `sources` parameter.

2021-07-21 20:34 UTC, lefou commented on mill-mima/src/com/github/lolgab/mill/mima/Mima.scala
> +    //    val pCustomizer = resolutionCustomizer()
The `resolutionCustomizer` is relatively new API, and was only introduce after mill 0.9.3. So, we can't use it, but we should use it once we provide a version for the next mill major (e.g. 0.10).

2021-07-21 20:36 UTC, lefou commented on mill-mima/src/com/github/lolgab/mill/mima/Mima.scala
> +        p._1.exclude("*" -> "*") -> p._2.iterator.next
You are right. Yet, my motivation to stick to the exclude-approach was, that the newly introduced `resolveSeparateDeps` can remain general purpose. We could even push it upstream once there is need for it.

2021-07-21 20:37 UTC, lefou commented on itest/src/simple/build.sc
> +  def mimaPreviousArtifacts = T(
Makes sense.

2021-07-21 21:22 UTC, lefou commented on itest/src/simple/build.sc
> +  // assert(curr.resolvedMimaPreviousArtifacts().size == 3)
Yeah, that works. I added as commit. In fact, it fails (with modifications) without the fix. It's a bit nasty though to deduce the correctness of the resolution process from the binary report.

2021-07-21 21:27 UTC, lefou commented on mill-mima/src/com/github/lolgab/mill/mima/Mima.scala
> +      sources: Boolean = false
It depends if we want to keep the `resolveSeparateDeps` general purpose (hence copy-n-paste friendly) or not. I agree, in this concrete case the `source` parameter is not yet needed.

2021-07-22 08:56 UTC, lolgab commented on mill-mima/src/com/github/lolgab/mill/mima/Mima.scala
> +    //    val pCustomizer = resolutionCustomizer()
So later we can extract in Mill specific src directories. Cool!

2021-07-22 09:03 UTC, lefou commented on mill-mima/src/com/github/lolgab/mill/mima/Mima.scala
> +    //    val pCustomizer = resolutionCustomizer()
It's probably a good idea to extract this into it's own file and trait (`ExtraCoursierSupport`).

2021-07-22 09:16 UTC, lefou commented on mill-mima/src/com/github/lolgab/mill/mima/Mima.scala
> +    //    val pCustomizer = resolutionCustomizer()
Done

2021-07-23 15:51 UTC, lolgab requested changes
Left some comments about visibility again (sorry, I'm kinda obsessed by API minimality)
Also left some comments on the test.

Thank you! After merging this one we can then publish a new version and start to add it to the com-lihaoyi repositories with more versions and a better API ( thanks to the `mimaPreviousVersions` you added. 🎉 )

2021-07-23 15:51 UTC, lolgab commented on mill-mima/src/com/github/lolgab/mill/mima/Mima.scala
> +        p._1.exclude("*" -> "*") -> p._2.iterator.next
I agree that it's interesting to have a utility to resolve separate dependencies. On the other hand, I think that a MiMa specific plugin is not the right place to expose such functionality.
I would leave an ad hoc trait as you did, but with private visibility so users don't need to know about it.
It would be nice to have it upstream. In case Mill adds it we can change the implementation to use that implementation instead of our bespoke one.

Once this is private and not shared, we can then use `.withTransitive(false)`

2021-07-23 15:51 UTC, lolgab commented on mill-mima/src/com/github/lolgab/mill/mima/ExtraCoursierSupport.scala
> +trait ExtraCoursierSupport extends CoursierModule {
Can this be `private[mima]` as I stated in the other comment?

2021-07-23 15:51 UTC, lolgab commented on mill-mima/src/com/github/lolgab/mill/mima/ExtraCoursierSupport.scala
> +    //    val pCustomizer = resolutionCustomizer()
Nice to have this comment so we know why this is commented 👌

2021-07-23 15:51 UTC, lolgab commented on itest/src/multi-previous-versions/build.sc
> +}
I think we can remove this test since the two previous versions have the same code and so they give the same result regardless of the bug being fixed or not.

2021-07-23 15:51 UTC, lolgab commented on itest/src/multi-previous-versions/build.sc
> +}
Removing the `curr2` test as I stated in the other comment you can remove this object too.

2021-07-23 15:51 UTC, lolgab commented on itest/src/multi-previous-versions/build.sc
> +  def publishVersion = "0.0.1"
You can move this line to `curr` once you delete `curr2`

2021-07-23 15:51 UTC, lolgab commented on build.sc
> +          TestInvocation.Targets(Seq("verifyFail"), expectedExitCode = 1)
After changing the test as I stated in the other comment, you can rename `verifyFail` to `verify` as in the other tests.

2021-07-24 07:57 UTC, lefou commented on build.sc
> +          TestInvocation.Targets(Seq("verifyFail"), expectedExitCode = 1)
No, we still need `verify` to place the `assert`s we want to check. Actually, the other test are doing it wrong, as an verify target with `expectedExitCode = 1` does no longer reveal if the expected MiMa report failed or one of the other assertions.

2021-07-25 08:12 UTC, lolgab commented on build.sc
> +          TestInvocation.Targets(Seq("verifyFail"), expectedExitCode = 1)
Oh, gotcha! Thank you for the explanation!

2021-07-25 08:13 UTC, lolgab approved these changes
Thank for you for the contribution and for addressing all the comments!
I think now we can release a really usable version!

2021-07-25 08:14 UTC, merged